import type { Metadata } from "next";
import { Be_Vietnam_Pro, Cairo } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Locale } from "@/i18n.config";
import { Directions, Languages } from "@/constants/enums";
import Footer from "@/components/footer";

const Vietnam = Be_Vietnam_Pro({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const cairo = Cairo({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Rawahil Dawlia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}>) {
  const locale = (await params).locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body className={`${Vietnam.className} ${cairo.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
